[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "E9M6Zj3yMrQ8h4f6Lw94EUxuhEFnFVJKgfQNPnpQRgYu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jasonaw/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
